apiVersion: apps/v1
kind: Deployment
metadata:
  name: bag-react
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bag-react
  template:
    metadata:
      labels:
        app: bag-react
    spec:
      securityContext:
        runAsGroup: 359
        fsGroup: 359
      containers:
        - name: react
          image: registry.rcaldas.com/boragora/bag-react:0.0.2
          imagePullPolicy: Always
          command: ["npm", "start"]
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "150Mi"
              cpu: "50m"
            limits:
              memory: "1400Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: bag
          env:
            - name: REACT_APP_BASE_API_URL
              value: https://react.boragora.app/api
          volumeMounts:
            - name: src
              mountPath: /app/src
            - name: public
              mountPath: /app/public
      volumes:
        - name: src
          hostPath:
            path: /var/dev/boragora/bag-react/src
        - name: public
          hostPath:
            path: /var/dev/boragora/bag-react/public
      nodeSelector:
        kubernetes.io/hostname: bg
